  name: 'push to server'
  on:
    push:
      branches:
        - main
  jobs:
      cd:
           runs-on: ubuntu-latest
           steps:
             - name: 'set ssh keys'
               run: |
                 mkdir -p ~/.ssh
                 echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                 chmod 600 ~/.ssh/id_rsa
             - name: 'deploy to server'
               run: |
                 echo 'yes' | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
                   cd apps
                   cd rati-rukhadze-epic-movie-quotes-back
                   git pull origin main
                   php artisan queue:work
                   php artisan optimize:clear
                   php artisan config:clear
                   php artisan cache:clear
                   php artisan config:cache
                 EOF
